### ISSUE TITLE
https://github.com/sspkudx/papers/blob/master/big-data/hive.md 有完整版或者加长版的么

### ISSUE THREAD

**Issue by notfresh** [sspkudx/papers#1]
我之前没用过Hive, 可能就感觉有点短.

**Comment by notfresh** [comment]
https://github.com/sspkudx/papers/blob/master/big-data/hive.md

**Comment by notfresh** [comment]
一个小小的建议, 学弟可以把自己的 github ID 加上, 如果有人想讨论了, 可以找到你.

**Comment by notfresh** [comment]
@zbtzbtzbt

**Comment by zbtzbtzbt** [comment]
点头像看得到id的。。

**Comment by zbtzbtzbt** [comment]
hive原文就很短，它其实就是一个将sql任务转为mapreduce的框架而已。。没有自己的存储，计算用的hadoop里面的mapreduce
[http://www.vldb.org/pvldb/vol2/vldb09-938.pdf](http://www.vldb.org/pvldb/vol2/vldb09-938.pdf)

**Comment by notfresh** [comment]
> 点头像看得到id的。。

哪个仓库下, 没找到啊

hive的原文又让我知道还有更短的论文了!!

**Comment by notfresh** [comment]
头像换的不错, 感觉气象焕然一新啊! 感觉可以再摇人了, 学弟是会搞事的人

**Comment by notfresh** [comment]
我再找些熟悉的同学进来

**Comment by zbtzbtzbt** [comment]
看.md文件时，上面有contributer，可以看到id。
